name: Deploy Node.js to GCP Compute Engine

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set Google Cloud Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Export GitHub PAT
        run: echo "GITHUB_PAT=${{ secrets.DEPLOY_PAT }}" >> $GITHUB_ENV

      - name: Export GitHub PAT
        run: echo "DEPLOY_PAT=${{ secrets.DEPLOY_PAT }}" >> $GITHUB_ENV

      - name: Terraform
        run: mkdir secrets && echo ${{ secrets.GCP_KEY }} > ./secrets/credentials.json && TF_VAR_GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} TF_VAR_DEPLOY_PAT=${{ secrets.DEPLOY_PAT }} terraform init && terraform plan && terraform apply -auto-approve